file: 4-线性代数基础.ipynb  
site: github.com/IYATT-yx/learning  

Copyright (C) 2021 IYATT-yx (Zhao Hongfei, 赵洪飞)，2514374431@qq.com
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

## 矩阵基础操作

In [1]:
import numpy as np
import sympy as sp

### 列表

In [2]:
A = [[1,2,3],[4,5,6],[7,8,9]]
a = np.array(A)
print(A)
print(a)
print('矩阵类型：', type(a))

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
矩阵类型： <class 'numpy.ndarray'>


### 元组

In [3]:
B = ((1,2,3),(4,5,6),(7,8,9))
b = np.array(B)
print(B)
print(b)

((1, 2, 3), (4, 5, 6), (7, 8, 9))
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### 随机

In [4]:
# 元素在 [0,1) 之间 4x3 的矩阵
c = np.random.random((4,3))
print(c)

[[0.62072168 0.8971626  0.82474719]
 [0.65957636 0.65034318 0.077756  ]
 [0.82979978 0.8786114  0.21138965]
 [0.96937265 0.73978475 0.29791096]]


In [5]:
# 四维 2x2x2x2
d = np.random.random((2,2,2,2))
print(d)

[[[[0.1193419  0.5919589 ]
   [0.6114497  0.38178968]]

  [[0.07616742 0.6147575 ]
   [0.1010228  0.27287313]]]


 [[[0.58324184 0.5475117 ]
   [0.87303633 0.02191231]]

  [[0.58039221 0.72173828]
   [0.2741069  0.61715421]]]]


In [6]:
# 整数元素的矩阵
e = np.random.randint(0, 100, (2,2), dtype=np.int32)  # 元素在 [0,100] 之间，类型为 32 位整数的，大小为 2x2 的矩阵
print(e)

[[ 5 75]
 [34 56]]


### 改变形状

In [7]:
F = [1,2,3,4,5,6,7,8,9,10,11,12]
f = np.array(F)
print('{} 的形状为 {}'.format(f, f.shape))

[ 1  2  3  4  5  6  7  8  9 10 11 12] 的形状为 (12,)


In [8]:
# 修改形状但是必须保证修改后的元素总个数和原来一样
ff = f.reshape(2,6)
print('{} 的形状为 {}'.format(ff, ff.shape))

fff = f.reshape(3,-1)  # 指定一个，另一个自动计算
print('{} 的形状为 {}'.format(fff, fff.shape))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]] 的形状为 (2, 6)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 的形状为 (3, 4)


### 矩阵元素存取

In [9]:
print(fff)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [10]:
print(fff[0])  # 获取第一行

[1 2 3 4]


In [11]:
print(fff[0:2])  # 获取 1～2 行 (0～1 前闭后开)

[[1 2 3 4]
 [5 6 7 8]]


In [12]:
print(fff[[0,2]])  # 获取 1 和 3 行

[[ 1  2  3  4]
 [ 9 10 11 12]]


In [13]:
print(fff[:,1])  # 获取第 2 列

[ 2  6 10]


In [14]:
print(fff[:,1:3])  # 获取 2～3 列 (2~4 前闭后开)

[[ 2  3]
 [ 6  7]
 [10 11]]


In [15]:
print(fff[:,[1,3]])  # 获取第 2 列和第 4 列

[[ 2  4]
 [ 6  8]
 [10 12]]


In [16]:
print(fff[1,3])  # 获取第 2 行第 4 列的元素

# 修改
fff[1,3] = 100
print(fff)

8
[[  1   2   3   4]
 [  5   6   7 100]
 [  9  10  11  12]]


## 特殊矩阵

### 零数组

In [17]:
a = np.zeros(4)
print(a)
print(a.shape)

[0. 0. 0. 0.]
(4,)


### 零矩阵

In [18]:
b = np.zeros((3,4))
print(b)
print(b.shape)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(3, 4)


### 零向量

In [19]:
c = np.array([np.zeros(10)])  # 行向量
print(c)
print(c.shape)

d = c.reshape((10,-1))  # 转列向量
print(d)
print(d.shape)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
(1, 10)
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
(10, 1)


### 方阵

In [20]:
# 行列数相等的矩阵
e = np.random.randint(1, 32, size=[3,3])
print(e)
print(e.shape)

[[15  4  4]
 [11 28 14]
 [27 25 23]]
(3, 3)


### 单位矩阵

In [21]:
E = np.eye(4)
print(E)
print(E.shape)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
(4, 4)


In [22]:
I = np.identity(3)
print(I)
print(I.shape)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
(3, 3)


### 对角矩阵

In [23]:
F = [1,2,3]
f = np.diag(F)  # 创建对角矩阵

print(f)
print(f.shape)

print('\n获取对角矩阵的元素:')
ff = np.diag(f)
print(ff)
print(ff.shape)

[[1 0 0]
 [0 2 0]
 [0 0 3]]
(3, 3)

获取对角矩阵的元素:
[1 2 3]
(3,)


### 上三角矩阵

In [24]:
g = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

In [25]:
gg = np.triu(g, 0)
print(gg)

[[ 1  2  3  4]
 [ 0  6  7  8]
 [ 0  0 11 12]
 [ 0  0  0 16]]


In [26]:
gg = np.triu(g, 1)  # 对角线向上偏移
print(gg)

[[ 0  2  3  4]
 [ 0  0  7  8]
 [ 0  0  0 12]
 [ 0  0  0  0]]


### 下三角矩阵

In [27]:
gg = np.tril(g, 0)
print(gg)

[[ 1  0  0  0]
 [ 5  6  0  0]
 [ 9 10 11  0]
 [13 14 15 16]]


In [28]:
gg = np.tril(g, 1)
print(gg)

[[ 1  2  0  0]
 [ 5  6  7  0]
 [ 9 10 11 12]
 [13 14 15 16]]


### 对称矩阵

矩阵元素关于主对角线对称，如：  
$$\left[
\begin{matrix}
    1 & 2 & 3 \\
    2 & 5 & 6 \\
    3 & 6 & 9
\end{matrix}
\right]$$

### 同型矩阵

行列数相同的两个矩阵。

In [29]:
a = np.random.randint(0, 5, (2,3))
b = np.random.randint(0, 5, (2,3))

print(a)
print(a.shape)
print(b)
print(b.shape)

if a.shape == b.shape:
    print('a 和 b 为同型矩阵')

[[3 3 0]
 [3 1 1]]
(2, 3)
[[1 0 1]
 [0 0 4]]
(2, 3)
a 和 b 为同型矩阵


### 矩阵相等

In [30]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3],[4,5,6]])
c = np.array([[6,2,3],[4,5,6]])

print('a 和 b 是否相等：{}'.format(np.allclose(a, b)))
print('a 和 c 是否相等：{}'.format(np.allclose(a, c)))

a 和 b 是否相等：True
a 和 c 是否相等：False


## 矩阵基本运算

### 加减

In [31]:
a = np.random.randint(0, 10, (3,3))
b = np.random.randint(0, 10, (3,3))

print(a)
print(b)

[[1 7 9]
 [9 1 2]
 [5 2 3]]
[[4 6 9]
 [6 2 1]
 [2 8 0]]


In [32]:
print(a + b)

[[ 5 13 18]
 [15  3  3]
 [ 7 10  3]]


In [33]:
print(a - b)

[[-3  1  0]
 [ 3 -1  1]
 [ 3 -6  3]]


### 数乘

In [34]:
print(2 * a)

[[ 2 14 18]
 [18  2  4]
 [10  4  6]]


### 乘法

前矩阵列数需要等于后矩阵的行数

性质：  
1.不满足交换律；  
2.(AB)C=A(BC)  
3.A(B+C)=AB+AC  
4.(B+C)A=BA+CA  
5.$\lambda$AB=($\lambda$A)B=A($\lambda$B)

$\left[
\begin{matrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{matrix}
\right]$
$\left[
\begin{matrix}
1 & 2 \\
3 & 4 \\
5 & 6
\end{matrix}
\right]$
=
$\left[
\begin{matrix}
1x1+2x3+3x5 & 1x2+2x4+3x6 \\
4x1+5x3+6x5 & 4x2+5x4+6x6
\end{matrix}
\right]$
=
$\left[
\begin{matrix}
22 & 28 \\
49 & 64
\end{matrix}
\right]$

In [35]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2],[3,4],[5,6]])
print(np.dot(a, b))

[[22 28]
 [49 64]]


In [36]:
a = np.mat([[1,2,3],[4,5,6]])
b = np.mat([[1,2],[3,4],[5,6]])

print(a * b)
print(np.dot(a, b))

[[22 28]
 [49 64]]
[[22 28]
 [49 64]]


### 同型矩阵对应相乘

In [37]:
a = np.array([[1,2],[3,4]])
b = np.array([[4,3],[2,1]])

print(a * b)
print(np.multiply(a, b))

[[4 6]
 [6 4]]
[[4 6]
 [6 4]]


### 乘方

In [38]:
a = np.array([[1,2],[3,4]])
print(a.dot(a).dot(a))  # a^3

[[ 37  54]
 [ 81 118]]


In [39]:
b = np.mat([[1,2],[3,4]])
print(b ** 3)

[[ 37  54]
 [ 81 118]]


若 AB $\neq$ BA，有：  
$$(A+B)^2=A^2+AB+BA+B^2\neq A^2+2AB+B^2$$
$$(A+B)(A-B)=A^2-AB+BA-B^2\neq A^2-B^2$$
$$(A\times B)^2=(AB)(AB)\neq A^2B^2 $$

$
A=
\left[
\begin{matrix}
1 & 2 \\
3 & 4
\end{matrix}
\right]
, B=
\left[
\begin{matrix}
1 & 0 \\
2 & 3
\end{matrix}
\right]
$

In [40]:
A = np.array([[1,2],[3,4]])
B = np.array([[1,0],[2,3]])

print('(A+B)^2=\n%s' %(A + B).dot(A + B))
print('A^2+AB+BA+B^2=\n%s' %(A.dot(A) + A.dot(B) + B.dot(A) + B.dot(B)))
print('A^2+2AB+B^2=\n%s\n' %(A.dot(A) + 2 * A.dot(B) + B.dot(B)))

print('(A+B)(A-B)=\n%s' %(A + B).dot(A - B))
print('A^2-AB+BA-B^2=\n%s' %(A.dot(A) - A.dot(B) + B.dot(A) - B.dot(B)))
print('A^2-B^2=\n%s\n' %(A.dot(A) - B.dot(B)))

print('(AxB)^2=\n%s' %(A.dot(B).dot(A.dot(B))))
print('(AB)(AB)=\n%s' %(A.dot(B).dot(A.dot(B))))
print('A^2B^2=\n%s' %(A.dot(A).dot(B.dot(B))))

(A+B)^2=
[[14 18]
 [45 59]]
A^2+AB+BA+B^2=
[[14 18]
 [45 59]]
A^2+2AB+B^2=
[[18 22]
 [45 55]]

(A+B)(A-B)=
[[ 2  6]
 [ 7 17]]
A^2-AB+BA-B^2=
[[ 2  6]
 [ 7 17]]
A^2-B^2=
[[ 6 10]
 [ 7 13]]

(AxB)^2=
[[ 91 102]
 [187 210]]
(AB)(AB)=
[[ 91 102]
 [187 210]]
A^2B^2=
[[ 87  90]
 [191 198]]


### 转置矩阵

性质：  
$(A^T)^T=A$  
$(A+B)^T=A^T+b^T$  
$(\lambda A)^T=\lambda A^T$  
$(AB)^T=B^TA^T$  
$(A_1A_2...A_n)^T=A_n^T...A_2^TA_1^T$

In [41]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
print(a.transpose())
print(a.T)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [42]:
# 对称矩阵创建

a = np.random.randint(0, 10, (3,3))  # 随机生成矩阵
print(a)
b = np.triu(a)  # 上三角
print(b)
c = b.transpose()  # 上三角的逆矩阵
print(c)
d = b + c - np.diag(np.diag(a))
print(d)

[[6 5 9]
 [1 3 7]
 [4 2 4]]
[[6 5 9]
 [0 3 7]
 [0 0 4]]
[[6 0 0]
 [5 3 0]
 [9 7 4]]
[[6 5 9]
 [5 3 7]
 [9 7 4]]


### 逆矩阵

$对于 n 阶方阵，若存在 n 阶方阵 \mathrm{B}，使得：\mathrm{AB=BA=E}（单位矩阵），记作：\mathrm{B=A}^{-1}，\mathrm{A=B}^{-1}。若 \mathrm{A} 可逆，则其逆矩阵唯一。$

不是所有方阵都有逆矩阵，没有逆矩阵的方阵称为奇异矩阵或不可逆矩阵，有逆矩阵的方阵称为非奇异矩阵或可逆矩阵。注意可逆矩阵只能用于方阵。

性质：  
$(A^{-1})^{-1}=A$  
$(A^T)^{-1}=(A^{-1})^T$  
$(\lambda A)^{-1}=\frac{1}{\lambda}A^{-1},\lambda \neq 0$  
$(AB)^{-1}=B^{-1}A^{-1}$  

如：
$\left[
\begin{matrix}
1 & 2 \\
2 & 5
\end{matrix}
\right]$
$\left[
\begin{matrix}
5 & -2 \\
-2 & 1
\end{matrix}
\right]$
=
$\left[
\begin{matrix}
1 & 0 \\
0 & 1
\end{matrix}
\right]$
，且
$\left[
\begin{matrix}
5 & -2 \\
-2 & 1
\end{matrix}
\right]$
$\left[
\begin{matrix}
1 & 2 \\
2 & 5
\end{matrix}
\right]$
=
$\left[
\begin{matrix}
1 & 0 \\
0 & 1
\end{matrix}
\right]$
，则两个矩阵互为逆矩阵。

In [43]:
a = np.array([[1,2],[2,5]])

print(np.linalg.inv(a))

[[ 5. -2.]
 [-2.  1.]]


In [44]:
b = np.mat([[1,2],[2,5]])

print(np.linalg.inv(b))
print(b.I)

[[ 5. -2.]
 [-2.  1.]]
[[ 5. -2.]
 [-2.  1.]]


In [45]:
# 奇异矩阵
c = np.mat([[1,-4,0,2],[-1,2,-1,-1],[1,-2,3,5],[2,-6,1,3]])

try:
    c.I
except Exception as result:
    print(result)

Singular matrix


## 行列式

在线性代数中，行列式是基本的数学工具，有着重要的应用。行列式是一个算式，经过计算后就是数。行列式主要用于判断矩阵时候可逆及计算特征方程。

我的理解中可以看作是行列数相同的矩阵。

计算
$\mathrm{A}$
=
$\left|
\begin{matrix}
1 & -2 & 3 \\
-1 & 2 & 1 \\
-3 & -4 & -2
\end{matrix}
\right|$
的值。

In [46]:
A = np.array([[1,-2,3],[-1,2,1],[-3,-4,-2]])
print(np.linalg.det(A))

40.000000000000014


## 矩阵的秩

### 线性相关与线性无关

如：在矩阵
$\mathrm{A}=
\left[
\begin{matrix}
1 & 2 & -1 \\
3 & 2 & 5 \\
5 & 6 & 3
\end{matrix}
\right]$
中选取向量组
$k_1=
\left[
\begin{matrix}
1 \\
3 \\
5
\end{matrix}
\right]$
,
$k_2=
\left[
\begin{matrix}
2 \\
2 \\
6
\end{matrix}
\right]$
，设
$k_1
\left[
\begin{matrix}
1 \\
3 \\
5
\end{matrix}
\right]
+k_2
\left[
\begin{matrix}
2 \\
2 \\
6
\end{matrix}
\right]
=
\left[
\begin{matrix}
0 \\
0 \\
0
\end{matrix}
\right]$  
通过计算，$k_1=k_2=0$ 时，上式才能成立，所以，这两个向量构成的向量组是线性无关的（一个向量不能用另外一个向量表示）。  
若选取向量组
$k_1=
\left[
\begin{matrix}
1 \\
3 \\
5
\end{matrix}
\right]
,k_2=
\left[
\begin{matrix}
2 \\
2 \\
6
\end{matrix}
\right]
,k_3=
\left[
\begin{matrix}
-1 \\
5 \\
3
\end{matrix}
\right]
$
，当满足
$k_1
\left[
\begin{matrix}
1 \\
3 \\
5
\end{matrix}
\right]
+k_2
\left[
\begin{matrix}
2 \\
2 \\
6
\end{matrix}
\right]
+k_3
\left[
\begin{matrix}
-1 \\
5 \\
3
\end{matrix}
\right]
=
\left[
\begin{matrix}
0 \\
0 \\
0
\end{matrix}
\right]
$
时，  
可以满足$k_1=3, k_2=-2, k_3=-1$，所以上述 3 个向量线性相关，一个向量可以用另外两个向量表示，  
如
$\left[
\begin{matrix}
-1 \\
5 \\
3
\end{matrix}
\right]
=3x
\left[
\begin{matrix}
1 \\
3 \\
5
\end{matrix}
\right]
+(-2)x
\left[
\begin{matrix}
2 \\
2 \\
6
\end{matrix}
\right]
$
。

### 矩阵的秩

设矩阵 $\mathrm{A}=(a_{ij}）_{mxn}$,在 $\mathrm{A}$ 中任取 r 行 r 列交叉处元素，按相对位置组成 r 阶行列式 $(1\leq r \leq min\{m，n\})$，称 $\mathrm{A}$ 的一个 r 阶子式。

设矩阵 $\mathrm{A}=(a_{ij})_{mxn}$，有 r 阶式不为 0，任何 r+1 阶子式（如果存在的话）全为 0，则称 r 为矩阵的秩，记作 R($\mathrm{A}$) 或秩($\mathrm{A}$)。  
矩阵的秩是唯一的，零矩阵的秩为 0，非零矩阵的秩大于等于 1。

如：
$\mathrm{A}=
\left[
\begin{matrix}
-2 & 1 & 1 & 0 \\
1 & -2 & 1 & 3 \\
1 & 1 & -2 & -3
\end{matrix}
\right]
$  
$
\sim
\left[
\begin{matrix}
0 & -3 & 3 & 6 \\
1 & -2 & 1 & 3 \\
0 & 3 & -3 & -6
\end{matrix}
\right]
\sim
\left[
\begin{matrix}
1 & -2 & 1 & 3 \\
0 & -3 & 3 & 6 \\
0 & 0 & 0 & 0
\end{matrix}
\right]$
，非全 0 行数为 2，R(A)=2

In [47]:
A = np.array([[-2,1,1,0],[1,-2,1,3],[1,1,-2,-3]])
print('A=%s' %A)
print('R(A)=%d' %np.linalg.matrix_rank(A))

A=[[-2  1  1  0]
 [ 1 -2  1  3]
 [ 1  1 -2 -3]]
R(A)=2


### 线性方程组的解

设有 n 个未知数 m 个方程的线性方程组  
$\left\{
\begin{array}{lr}
    a_{11}x_1+a_{12}x_2+...+a_{1n}n_n=b_1 \\
    a_{21}x_1+a_{22}x_2+...+a_{2n}x_n=b_2 \\
    ... \\
    a_{m1}x_1+a_{m2}x_2+...+a_{mn}x_n=b_m
\end{array}
\right.$  
可以写成以向量 x 为未知元的向量方程： $\mathrm{A}x=\mathrm{b}$  
* 无解的充分必要条件是 $R(\mathrm{A})<R(\mathrm{A},\mathrm{b})$ ；
* 有无限多解的充分必要条件是 $R(\mathrm{A})=R(\mathrm{A},\mathrm{b})<n$ ;
* 有唯一解的充分必要条件是 $R(\mathrm{A})=R(\mathrm{A},\mathrm{b})=n$ 。


如：
$\left\{
\begin{array}{lr}
    x_2+x_3=0 \\
    x_1+x_3=3 \\
    x_1+x_2=-1
\end{array}
\right.$  
对增广矩阵 $\mathrm{B}=(\mathrm{A},\mathrm{b})$ 作初等行变换，有  
$\mathrm{B}=
\left[
\begin{matrix}
    0 & 1 & 1 & 0 \\
    1 & 0 & 1 & 3 \\
    1 & 1 & 0 & -1
\end{matrix}
\right]
\sim
\left[
\begin{matrix}
1 & 1 & 0 & -1 \\
1 & 0 & 1 & 3 \\
0 & 1 & 1 & 0
\end{matrix}
\right]
\sim
\left[
\begin{matrix}
1 & 1 & 0 & -1 \\
0 & -1 & 1 & 4 \\
0 & 1 & 1 & 0
\end{matrix}
\right]
\sim
\left[
\begin{matrix}
1 & 1 & 0 & -1 \\
0 & -1 & 1 & 4 \\
0 & 0 & 2 & 4
\end{matrix}
\right]$  
可知 R($\mathrm{A})=R(\mathrm{A},\mathrm{b})=3$ ,方程组有唯一解。

如：
$\left\{
\begin{array}{lr}
    -2x_1+x_2+x_3=0 \\
    x_1-2x_2+x_3=3 \\
    x_1+x_2-2x_3=-3
\end{array}
\right.$  
对增广矩阵 $\mathrm{B}=(\mathrm{A},\mathrm{b})$ 作初等行变换，有  
$\mathrm{B}\sim
\left[
\begin{matrix}
    1 & 1 & 2 & -3 \\
    0 & -3 & 3 & 6 \\
    0 & 0 & 0 & 0
\end{matrix}
\right]
\sim
\left[
\begin{matrix}
    1 & 0 & -1 & -1 \\
    0 & 1 & -1 & -2 \\
    0 & 0 & 0 & 0
\end{matrix}
\right]$
可知 R($\mathrm{A})=R(\mathrm{A},\mathrm{b})=2$ ,方程组有无限多解。  
得通解：
$\left\{
\begin{array}{lr}
x_1=x_3-1 \\
x_2=x_3-2
\end{array}
\right.$
($x_3$ 可取任意值)，  
即
$\left(
\begin{matrix}
x_1 \\
x_2 \\
x_3
\end{matrix}
\right)
=c
\left(
\begin{matrix}
1 \\
1 \\
1 \\
\end{matrix}
\right)
+
\left(
\begin{matrix}
-1 \\
-2 \\
0
\end{matrix}
\right)
，(c\in \mathrm{R})$

## 内积与正交

机器学习的许多算法都会用到内积的计算，内积可以用于判断两个向量时候正交，以及求向量间的距离等。

### 向量的内积

设有两个同型的 n 维列向量
$\mathrm{x}=
\left[
\begin{matrix}
x_1 \\
x_2 \\
. \\
. \\
. \\
x_n
\end{matrix}
\right]
，y=
\left[
\begin{matrix}
y_1 \\
y_2 \\
. \\
. \\
. \\
y_n
\end{matrix}
\right]$
，令$\mathrm{[x,y]=x_1y_1+x_2y_2+...+x_ny_n}$，称 $\mathrm{[x,y]}$ 为向量 $\mathrm{x}$ 和向量 $\mathrm{y}$ 的内积。内积也可以用 $\mathrm{x\cdot y}$ 表示。

内积可以用矩阵的乘法表示，
$[x,y]=[x_1x_2...x_n]
\left[
\begin{matrix}
y_1 \\
y_2 \\
. \\
. \\
. \\
y_n
\end{matrix}
\right]
=x^Ty$。

若 x,y 为 n 维行向量，
$[x,y]=[x_1x_2...x_n]
\left[
\begin{matrix}
y_1 \\
y_2 \\
. \\
. \\
. \\
y_n
\end{matrix}
\right]
=xy^T$。

性质：  
对称性：[x,y]=[y,x]  
线性性质：$[\lambda x,y]=\lambda[x.y], [x+y,z]=[x,z]+[y,z]$  
当 x=0 时，[x,x]=0,当 x$\neq$0 时，[x,x]>0

示例：
$a=
\left[
\begin{matrix}
1 \\
2 \\
3
\end{matrix}
\right]
,
b=\left[
\begin{matrix}
4 \\
5 \\
6
\end{matrix}
\right]$  
$[x,y]=x^Ty
=
\left[
\begin{matrix}
1 & 2 & 3
\end{matrix}
\right]
\left[
\begin{matrix}
4 \\
5 \\
6
\end{matrix}
\right]
=1\times4+2\times5+3\times6=32$

In [48]:
# 矩阵表示向量时
a = np.array([[1],[2],[3]])
b = np.array([[4],[5],[6]])
print('[a,b]=%d' %np.dot(a.T, b))
print(np.inner(a,b))

[a,b]=32
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [49]:
# 一维数组表示向量时
c = np.array([1,2,3])
d = np.array([4,5,6])
print(np.dot(c, d))
print(np.inner(c, d))

32
32


### 向量的长度

定义：$||x||=\sqrt{[x,x]}=\sqrt{x_1^2+x_2^2+...+x_n^2}$为 n 维向量 x 的长度，当 ||x||=1 时，称 x 为单位向量。

性质：  
非负性：||x||$\geq$0  
齐次性：$||\lambda x||=|\lambda|\cdot||x||$  
三角不等式：||x+y||$\leq$||x||+||y||

In [50]:
a = np.array([[0,3,4]])
a_len = np.linalg.norm(a)
print('{}的长度为{},单位向量为{}'.format(a, a_len, a / a_len))

[[0 3 4]]的长度为5.0,单位向量为[[0.  0.6 0.8]]


In [51]:
# 利用定义计算长度
print(np.sum(a ** 2) ** 0.5)

5.0


利用两个向量的内积和长度可以求出两个向量夹角的余弦值。  
$[x,y]=||x||*||y||*cos\theta$

示例：  
a = $(1,\sqrt3)$  
b = (1,0)  
夹角余弦可知为 0.5

In [52]:
a = np.array([[1, 3 ** 0.5]])
b = np.array([[1,0]])
c = np.dot(a, b.T) / (np.linalg.norm(a) * np.linalg.norm(b))
print(c)

[[0.5]]


### 向量的正交

当 [x,y]=0，即向量 $\mathrm{x}$ 和向量 $\mathrm{y}$ 的内积为 0，称向量 $\mathrm{x}$ 和 $\mathrm{y}$ 正交。  
正交可以理解为向量相互垂直。若 x=0，则 x 与任何向量都正交。

In [53]:
a = np.array([[1],[1],[1]])
b = np.array([[2],[-4],[2]])

if np.sum(a * b) == 0:
    print('a 和 b 正交')

a 和 b 正交


### 标准正交基

定义：  
设 $\mathrm{V}$ 为向量空间，设 $\mathrm{V}$ 中有 r 个向量 $\alpha_1,\alpha_2,...,\alpha_r$ 线性无关，而且 $\mathrm{V}$ 中任一向量都可由这 r 个向量表示，则称这 r 个向量构成的向量组 $\alpha_1,\alpha_2,...,\alpha_r$ 为向量空间 $\mathrm{V}$ 的基。这些向量的个数 r 称为向量空间 $\mathrm{V}$ 的维数，称 $\mathrm{V}$ 为 r 维向量空间。  
一个向量空间有很多个基，但是应用比较多的是标准正交基。  
若 $\alpha_1,\alpha_2,...,\alpha_r$ 是向量空间 $\mathrm{V}$ 中的基，$\alpha_1,\alpha_2,...,\alpha_r$ 均是单位向量，而且两两正交，则称 $alpha_1,\alpha2,...,\alpha_r$ 是 $\mathrm{V}$ 的标准正交基。  
标准正交基一定线性无关，且向量年年垂直。

如 
$\mathrm{e_1}=
\left[
\begin{matrix}
1 \\
0 \\
0 \\
0
\end{matrix}
\right]
, \mathrm{e_2}=
\left[
\begin{matrix}
0 \\
1 \\
0 \\
0
\end{matrix}
\right]
, \mathrm{e_3}=
\left[
\begin{matrix}
0 \\
0 \\
1 \\
0
\end{matrix}
\right]
, \mathrm{e_4}=
\left[
\begin{matrix}
0 \\
0 \\
0 \\
1
\end{matrix}
\right]
$
是四维空间 $\mathrm{R^4}$ 的一个标准正交基。

定义：  
若 n 阶方阵 $\mathrm{A}$ 满足 $\mathrm{A^TA=E}$ 或 $\mathrm{AA^T=E}$，则称 $\mathrm{A}$ 为正交矩阵，简称正交阵。  
如果是在复数范围内满足上式，则称 $\mathrm{A}$ 为酉（you）矩阵。酉矩阵常用于奇异值分解（SVD）中，正交矩阵是实数特殊化的酉矩阵。

示例：  
验证方阵 
$\mathrm{A}=
\left[
\begin{matrix}
0 & 1 & 0 \\
\frac{1}{\sqrt2} & 0 & \frac{1}{\sqrt2} \\
-\frac{1}{\sqrt2} & 0 & \frac{1}{\sqrt2}
\end{matrix}
\right]$
为一个正交矩阵。

In [54]:
a = np.array([[0,1,0],[1/2**0.5,0,1/2**0.5],[-1/2**0.5,0,1/2**0.5]])
np.round(a.dot(a.T))  # 内积计算四舍五入

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

性质：  
若 $\mathrm{A}$ 是正交矩阵，则 $\mathrm{A^{-1}}$ 和 $\mathrm{A^T}$ 也是正交矩阵；若 $\mathrm{A}$ 和 $\mathrm{B}$ 是正交矩阵，则 $\mathrm{AB}$ 也是正交矩阵。

## 线性代数的实际应用

### 一 将某线性系统用下面的线性方程组表示，求未知量 x、y、z 的值。

$\left\{
\begin{array}{lr}
x+2y+z=7 \\
2x-y+3z=7 \\
3x+y+2z=18
\end{array}
\right.$

求出系数矩阵的增广矩阵的秩

In [55]:
# 系数矩阵
A = np.array([[1,2,1],[2,-1,3],[3,1,2]])
B = np.array([[7],[7],[18]])
# 增广矩阵
AB = np.hstack((A,B))

print('系数矩阵 A 的秩: %d' %(np.linalg.matrix_rank(A)))
print('增广矩阵 AB 的秩: %d' %(np.linalg.matrix_rank(AB)))

系数矩阵 A 的秩: 3
增广矩阵 AB 的秩: 3


R(A)=R(A,B)=3，有唯一解。

 方法一：  
 $$AX=B$$
 $$\Rightarrow A^{-1}AX=A^{-1}B$$
 $$\Rightarrow X=A^{-1}B$$

In [56]:
A_I = np.linalg.inv(A)
X = A_I.dot(B)
print('解得：\n{}'.format(X))

解得：
[[ 7.]
 [ 1.]
 [-2.]]


方法二：

In [57]:
X = np.linalg.solve(A, B)  # A 需要为非奇异矩阵
print('解得：\n{}'.format(X))

解得：
[[ 7.]
 [ 1.]
 [-2.]]


方法三：

In [58]:
x, y, z = sp.symbols('x y z')
result = sp.solve([x+2*y+z-7,2*x-y+3*z-7,3*x+y+2*z-18], [x,y,z])  # 化为 = 0 的式子
print(result)

{x: 7, y: 1, z: -2}
